# action.yml
name: "Run RepoAgent"
description: "An action to run RepoAgent, generate project documentation, and commit changes with configurable environment variables."
author: "Arno Edwards"

branding:
  icon: code
  color: green

permissions:
  contents: write  # Allows pushing changes to the repository

inputs:
  openai_base_url:
    description: "The base URL for OpenAI API"
    required: false
  openai_api_key:
    description: "The API key for OpenAI API"
    required: true
  model:
    description: "Model name to use for LLM, such as 'gpt-4o-mini'"
    required: false
  temperature:
    description: "Sampling temperature for generating responses. Lower values make the model more deterministic."
    required: false
  request_timeout:
    description: "Maximum request timeout in seconds for each API call"
    required: false
  target_repo:
    description: "Directory path for the target repository to analyze"
    required: false
  hierarchy_name:
    description: "The name of the directory to store project documentation records"
    required: false
  markdown_docs_name:
    description: "The directory name where markdown documentation is stored"
    required: false
  ignore_list:
    description: "List of file paths to ignore during analysis"
    required: false
  language:
    description: "The language to use for generated documentation"
    required: false
  max_thread_count:
    description: "Maximum number of threads to use during processing"
    required: false
  log_level:
    description: "Log level for logging information (e.g., INFO, DEBUG, ERROR)"
    required: false

runs:
  using: "docker"
  image: "docker://ghcr.io/umpire2018/setup-repoagent:main"
